# docker run --name api-iaki-pg -e POSTGRESQL_USERNAME=janio -e POSTGRESQL_PASSWORD=j2240 
# -e POSTGRESQL_DATABASE=apiiaki -p 5432:5432 bitnami/postgresql

version: '3'

services:
  api-iaki-pg: 
      image: bitnami/postgresql
      ports: 
        - 5432:5432 
      environment:
        - POSTGRESQL_USERNAME=janio
        - POSTGRESQL_PASSWORD=j2240
        - POSTGRESQL_DATABASE=apiiaki